angular
    .module('game.systems', [
        'game.systems.camera',
        'game.systems.collisionReporter',
        'game.systems.helper',
        'game.systems.light',
        'game.systems.nameMesh',
        'game.systems.network',
        'game.systems.particles',
        'game.systems.proctree',
        'game.systems.quad',
        'game.systems.rigidBody',
        'game.systems.octree',
        'game.systems.script',
        'game.systems.shadow',
        'game.systems.sound',
        'game.systems.sprite',
        'game.systems.wieldItem',
    ]);
