angular
    .module('prefabs', [
        'prefabs.achievementTrigger',
        'prefabs.character',
        'prefabs.crystal',
        'prefabs.damageZone',
        'prefabs.mediumFire',
        'prefabs.mediumSmoke',
        'prefabs.movingPlatform',
        'prefabs.torch',
        'prefabs.teleportEntrance',
        'prefabs.teleportExit',
        'prefabs.bunny',
        'prefabs.spawnZone',
        'prefabs.spawnPoint',
        'prefabs.proctree',
        'prefabs.waterFountain',
        'prefabs.worldMesh'
    ]);
