angular
    .module('server.services', [
        'server.services.accounts',
        'server.services.achievements',
        'server.services.activeWorlds',
        'server.services.braintree',
        'server.services.character',
        'server.services.chat',
        'server.services.cheats',
        'server.services.entities',
        'server.services.game',
        'server.services.hipchat',
        'server.services.inspect',
        'server.services.items',
        'server.services.ironblood',
        'server.services.profiler',
        'server.services.servers',
        'server.services.zones'
    ]);
